export const MAIN_PAGE = '/'
export const DRAFT_PAGE = '/draft'
export const EDIT_TRAVEL = '/edittravel'
export const TRAVEL_DIARY_PAGE = '/travels'
export const PLANNED_TRAVEL_PAGE = '/plannedtravel'
